### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

1.Data Creation :

We’ll create three arrays:

In [ ]:
import numpy as np

# Students Data(5 students)
students = np.array([1, 2, 3, 4, 5])

# Subjects Data(4 subjects)
subjects = np.array([101, 102, 103, 104])

# Marks of 5 students in 4 subjects
marks = np.array([
    [78, 85, 90, 66],
    [88, 79, 92, 81],
    [84, 91, 87, 77],
    [70, 65, 80, 89],
    [95, 88, 92, 99]
])
print("Students:", students)
print("Subjects:", subjects)
print("Marks:\n",marks)



Students: [1 2 3 4 5]
Subjects: [101 102 103 104]
Marks:
 [[78 85 90 66]
 [88 79 92 81]
 [84 91 87 77]
 [70 65 80 89]
 [95 88 92 99]]


2.Data Exploration :

Checking properties of arrays.

In [ ]:
print("\nMarks Array Properties:")
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Size:", marks.size)
print("Data Type:", marks.dtype)



Marks Array Properties:
Shape: (5, 4)
Dimensions: 2
Size: 20
Data Type: int64


3.Data Transformation :

Reshape or reorganize marks.


In [ ]:
# Flatten marks to 1D
marks_flat = marks.flatten()

# Reshape back to (4,5)
marks_reshaped = marks.reshape(4, 5)

print("Flattened Marks:", marks_flat)
print("Reshaped Marks:\n", marks_reshaped)


Flattened Marks: [78 85 90 66 88 79 92 81 84 91 87 77 70 65 80 89 95 88 92 99]
Reshaped Marks:
 [[78 85 90 66 88]
 [79 92 81 84 91]
 [87 77 70 65 80]
 [89 95 88 92 99]]


4.Data Combination :

Simulate adding new students or subjects.

In [ ]:
# New student (6) with marks
new_student_marks = np.array([[82, 79, 88, 90]])
marks = np.vstack([marks, new_student_marks])   # add row

# Add new subject (5) scores for all students
new_subject_marks = np.array([[75], [89], [83], [78], [94], [88]])
marks = np.hstack([marks, new_subject_marks])   # add column

print("Updated Marks (after adding student & subject):\n", marks)


Updated Marks (after adding student & subject):
 [[78 85 90 66 75]
 [88 79 92 81 89]
 [84 91 87 77 83]
 [70 65 80 89 78]
 [95 88 92 99 94]
 [82 79 88 90 88]]


5.Data Modification :

Update or analyze data.

In [ ]:
# Update: increase all marks of student 3 by +5
marks[2] += 5

# Remove a student (e.g., 4)
marks = np.delete(marks, 3, axis=0)

# Unique marks
unique_marks = np.unique(marks)

print("Updated Marks:\n", marks)
print("Unique Marks:", unique_marks)


Updated Marks:
 [[78 85 90 66 75]
 [88 79 92 81 89]
 [89 96 92 82 88]
 [95 88 92 99 94]
 [82 79 88 90 88]]
Unique Marks: [66 75 78 79 81 82 85 88 89 90 92 94 95 96 99]


6.Data Type Handling :

Demonstrate type conversion.

In [ ]:
# Convert to float
marks_float = marks.astype(float)

# Convert to string
marks_str = marks.astype(str)

print("Float Type Marks:\n", marks_float)
print("String Type Marks:\n", marks_str)


Float Type Marks:
 [[78. 85. 90. 66. 75.]
 [88. 79. 92. 81. 89.]
 [89. 96. 92. 82. 88.]
 [95. 88. 92. 99. 94.]
 [82. 79. 88. 90. 88.]]
String Type Marks:
 [['78' '85' '90' '66' '75']
 ['88' '79' '92' '81' '89']
 ['89' '96' '92' '82' '88']
 ['95' '88' '92' '99' '94']
 ['82' '79' '88' '90' '88']]


7.Copy and View Behavior :

Show the difference between copy and view.

In [ ]:
# View (shares data)
marks_view = marks.view()
marks_view[0, 0] = 999

# Copy (independent data)
marks_copy = marks.copy()
marks_copy[0, 1] = 555
print("original Marks:\n",marks)
print("Original Marks after modifying VIEW:\n", marks)
print("Original Marks after modifying COPY:\n", marks)


original Marks:
 [[999  85  90  66  75]
 [ 88  79  92  81  89]
 [ 89  96  92  82  88]
 [ 95  88  92  99  94]
 [ 82  79  88  90  88]]
Original Marks after modifying VIEW:
 [[999  85  90  66  75]
 [ 88  79  92  81  89]
 [ 89  96  92  82  88]
 [ 95  88  92  99  94]
 [ 82  79  88  90  88]]
Original Marks after modifying COPY:
 [[999  85  90  66  75]
 [ 88  79  92  81  89]
 [ 89  96  92  82  88]
 [ 95  88  92  99  94]
 [ 82  79  88  90  88]]
